# Generated by Django 4.1.5 on 2023-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_city_code_alter_country_code_alter_state_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='omnipro_city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='omnipro_country',
        ),
        migrations.AlterModelTable(
            name='state',
            table='omnipro_state',
        ),
    ]
