# Generated by Django 4.1.5 on 2023-01-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_city_table_alter_country_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
