# Generated by Django 4.1.5 on 2023-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='omnipro_store',
        ),
    ]
