# Generated by Django 4.1.5 on 2023-01-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('favorite_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.state')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
