# Generated by Django 4.1.5 on 2023-01-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_code'),
        ('country', '0002_alter_city_code_alter_country_code_alter_state_code_and_more'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_id', to='country.city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='country.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='favorite_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_store', to='store.store'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='country.state'),
        ),
    ]
