# Generated by Django 4.1.5 on 2023-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_city_id_alter_client_country_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='omnipro_client',
        ),
    ]
